#!/bin/sh
# Tailscale mesh installer/updater for the Batocera Drone.
#
# This lives in the *versioned app bundle* (not scripts/) on purpose: both
# scripts/batocera_install.sh and the running Drone (self-update hook +
# the Controls page button, via app/device/tailnet_service.py) call it, so
# the install logic auto-updates with every Drone release exactly like
# app/service_bootstrap.sh does. scripts/batocera_install.sh delegates here
# rather than carrying its own copy -- one source of truth.
#
# Commands:
#   ensure   install if missing, upgrade to latest if already present
#   install  install only if missing (never touches existing binaries)
#   update   always upgrade to the latest stable
#   service  (re)write + enable the DRONE_TAILNET service, no download
#   status   print "installed=<0|1> version=<v> running=<0|1>"
#
# Upgrades are deliberately careful: the running tailscaled keeps working off
# its open file handles while we stage into a temp dir, we only swap + restart
# when the resolved version actually differs from what is installed, and we
# roll back to the saved previous binaries if the new daemon fails to come up.
# A VPN binary swap that strands a headless drone in another house is a much
# worse outcome than running one release behind.

set -u

TS_DIR="${DRONE_TAILSCALE_DIR:-/userdata/system/tailscale}"
TS_BIN="$TS_DIR/bin"
TS_BACKUP="$TS_DIR/bin.previous"
TS_SERVICE="${DRONE_TAILNET_SERVICE:-/userdata/system/services/DRONE_TAILNET}"
TS_SOCKET="${DRONE_TAILSCALE_SOCKET:-/var/run/tailscale/tailscaled.sock}"
TS_FALLBACK_VERSION="1.80.0"
LOG_PREFIX="[drone-tailscale]"

log() { echo "$LOG_PREFIX $*"; }
fail() { echo "$LOG_PREFIX $*" >&2; exit 1; }

detect_arch() {
  case "$(uname -m)" in
    x86_64) echo "amd64" ;;
    aarch64) echo "arm64" ;;
    armv7l|armv6l) echo "arm" ;;
    i686|i586) echo "386" ;;
    riscv64) echo "riscv64" ;;
    *) return 1 ;;
  esac
}

installed_version() {
  [ -x "$TS_BIN/tailscale" ] || return 1
  "$TS_BIN/tailscale" version 2>/dev/null | head -1 | tr -d '\r' | awk '{print $1}'
}

latest_version() {
  if [ -n "${DRONE_TAILSCALE_VERSION:-}" ]; then
    echo "$DRONE_TAILSCALE_VERSION"
    return 0
  fi
  curl -fsSL --connect-timeout 10 --max-time 30 "https://pkgs.tailscale.com/stable/?mode=json" 2>/dev/null \
    | sed -n 's/.*"Version":[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

daemon_running() {
  pgrep -f "$TS_BIN/tailscaled" >/dev/null 2>&1
}

# Write the DRONE_TAILNET service. Self-contained on purpose: unlike
# DRONE_SERVER (a thin shim into the versioned bundle), tailscaled supervision
# does not change with Drone releases.
write_service() {
  mkdir -p "$(dirname "$TS_SERVICE")" || return 1
  cat > "$TS_SERVICE" << 'TAILNETBLOCK'
#!/bin/sh
# Tailscale mesh daemon for the Batocera Drone fleet.
# Generated by app/install_tailscale.sh -- do not edit by hand.

TS_DIR="/userdata/system/tailscale"
STATE_DIR="$TS_DIR/state"
LOG_FILE="/userdata/system/logs/tailscaled.log"
PID_FILE="/tmp/drone-tailscaled.pid"
SOCKET_DIR="/var/run/tailscale"

is_running() {
  [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null
}

start() {
  if [ ! -x "$TS_DIR/bin/tailscaled" ]; then
    echo "[drone-tailnet] tailscaled is not installed at $TS_DIR/bin" >&2
    exit 1
  fi
  if is_running; then
    exit 0
  fi
  mkdir -p "$STATE_DIR" "$SOCKET_DIR" "$(dirname "$LOG_FILE")"
  modprobe tun 2>/dev/null || true
  if [ ! -c /dev/net/tun ]; then
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200 2>/dev/null || true
  fi
  TUN_FLAG="--tun=tailscale0"
  if [ ! -c /dev/net/tun ]; then
    # Inbound tailnet connections (phone -> drone UI, peer -> /peer/*) still
    # work via the userspace netstack; only this drone's own outbound dials to
    # tailnet addresses are unavailable, and transfers fall back to the other
    # transport tiers.
    echo "[drone-tailnet] /dev/net/tun unavailable; using userspace networking" >> "$LOG_FILE"
    TUN_FLAG="--tun=userspace-networking"
  fi
  # Byte offset of the log before launching, so wait_for_tun only ever reads
  # lines this start produced. The log is appended across restarts, and an
  # earlier boot's TUN errors must not condemn a run where the driver is fine.
  LOG_OFFSET=0
  [ -f "$LOG_FILE" ] && LOG_OFFSET=$(wc -c < "$LOG_FILE" 2>/dev/null | tr -d " ")
  launch "$TUN_FLAG"

  # The presence of /dev/net/tun is not proof that it works. Right after this
  # script mknod's the node (first boot, before the driver is ready), tailscaled
  # opens it happily and then fails every write with "Failed to write packets to
  # TUN device: input/output error" -- tailscale0 stays DOWN with no address, so
  # `tailscale status` and even `tailscale ping` look healthy while no IP traffic
  # reaches this drone at all. That is a silently half-broken tailnet: the Drone
  # can be seen but never dialed. Verify the interface actually came up, and fall
  # back to the userspace netstack (which still accepts inbound connections) if
  # it did not.
  if [ "$TUN_FLAG" = "--tun=tailscale0" ] && ! wait_for_tun; then
    echo "[drone-tailnet] tailscale0 did not come up; retrying with userspace networking" >> "$LOG_FILE"
    stop >/dev/null 2>&1
    sleep 1
    launch "--tun=userspace-networking"
  fi
  echo "[drone-tailnet] tailscaled started (pid $(cat "$PID_FILE"))"
}

launch() {
  nohup "$TS_DIR/bin/tailscaled" \
    --statedir="$STATE_DIR" \
    --socket="$SOCKET_DIR/tailscaled.sock" \
    "$1" >> "$LOG_FILE" 2>&1 &
  echo $! > "$PID_FILE"
}

# An enrolled node gets its 100.x address on tailscale0 within a few seconds.
# A node that has never been enrolled has no address to assign, so treat "the
# daemon is still alive and answering" as success there rather than forcing a
# pointless fallback on every pre-enrollment boot.
wait_for_tun() {
  i=0
  while [ "$i" -lt 12 ]; do
    if ip addr show tailscale0 2>/dev/null | grep -q "inet "; then
      return 0
    fi
    if tail -c "+$((LOG_OFFSET + 1))" "$LOG_FILE" 2>/dev/null \
      | grep -q "Failed to write packets to TUN device"; then
      return 1
    fi
    if [ "$i" -ge 5 ] && ! "$TS_DIR/bin/tailscale" --socket="$SOCKET_DIR/tailscaled.sock" status >/dev/null 2>&1; then
      # Not enrolled yet (status exits non-zero for "Logged out"): nothing will
      # ever be assigned, and kernel TUN is still the right mode for later.
      return 0
    fi
    sleep 1
    i=$((i + 1))
  done
  return 1
}

stop() {
  if [ -f "$PID_FILE" ]; then
    kill "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null || true
    rm -f "$PID_FILE"
  fi
  pkill -f "$TS_DIR/bin/tailscaled" 2>/dev/null || true
  echo "[drone-tailnet] tailscaled stopped"
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) stop; sleep 1; start ;;
  status)
    if is_running; then
      echo "[drone-tailnet] running (pid $(cat "$PID_FILE"))"
    else
      echo "[drone-tailnet] not running"
      exit 1
    fi
    ;;
  *) echo "Usage: $0 {start|stop|restart|status}"; exit 2 ;;
esac
TAILNETBLOCK
  chmod +x "$TS_SERVICE"
}

start_service() {
  if command -v batocera-services >/dev/null 2>&1; then
    batocera-services enable DRONE_TAILNET >/dev/null 2>&1 || true
    batocera-services start DRONE_TAILNET >/dev/null 2>&1 && return 0
  fi
  sh "$TS_SERVICE" start >/dev/null 2>&1
}

restart_service() {
  if command -v batocera-services >/dev/null 2>&1; then
    batocera-services stop DRONE_TAILNET >/dev/null 2>&1 || true
  fi
  sh "$TS_SERVICE" stop >/dev/null 2>&1 || true
  sleep 1
  start_service
}

# Wait for tailscaled to answer on its socket. A daemon that starts and
# immediately exits (bad binary for this arch, missing kernel support) must be
# treated as a failed upgrade, not a success.
wait_for_daemon() {
  i=0
  while [ "$i" -lt 15 ]; do
    if "$TS_BIN/tailscale" --socket="$TS_SOCKET" status >/dev/null 2>&1; then
      return 0
    fi
    # "Logged out"/"NeedsLogin" is a *healthy* daemon that simply isn't
    # enrolled -- the common case on a fresh install. status exits non-zero
    # for it, so fall back to a liveness check on the process itself.
    if daemon_running && [ "$i" -ge 3 ]; then
      return 0
    fi
    sleep 1
    i=$((i + 1))
  done
  return 1
}

download_into() {
  version="$1"
  arch="$2"
  dest="$3"
  tarball="tailscale_${version}_${arch}.tgz"
  tmp="/tmp/drone-tailscale-install.$$"
  log "Downloading Tailscale $version for $arch ..."
  if ! curl -fsSL --connect-timeout 10 --max-time 300 -o "$tmp.tgz" "https://pkgs.tailscale.com/stable/$tarball"; then
    rm -f "$tmp.tgz"
    log "Could not download $tarball."
    return 1
  fi
  mkdir -p "$tmp"
  if ! tar -xzf "$tmp.tgz" -C "$tmp"; then
    rm -rf "$tmp" "$tmp.tgz"
    log "Could not extract $tarball."
    return 1
  fi
  if [ ! -f "$tmp"/tailscale_*/tailscaled ] || [ ! -f "$tmp"/tailscale_*/tailscale ]; then
    rm -rf "$tmp" "$tmp.tgz"
    log "$tarball did not contain the expected binaries."
    return 1
  fi
  mkdir -p "$dest"
  cp "$tmp"/tailscale_*/tailscaled "$tmp"/tailscale_*/tailscale "$dest/" || {
    rm -rf "$tmp" "$tmp.tgz"
    return 1
  }
  chmod 755 "$dest/tailscaled" "$dest/tailscale"
  rm -rf "$tmp" "$tmp.tgz"
  return 0
}

do_install() {
  arch="$(detect_arch)" || fail "Unsupported architecture for Tailscale static binaries: $(uname -m)"
  version="$(latest_version)"
  if [ -z "$version" ]; then
    version="$TS_FALLBACK_VERSION"
    log "Could not discover the current Tailscale version; using pinned fallback $version."
  fi
  download_into "$version" "$arch" "$TS_BIN" || fail "Tailscale install failed."
  log "Installed tailscaled + tailscale $version to $TS_BIN"
  write_service || fail "Could not write $TS_SERVICE"
  log "Created service: $TS_SERVICE"
  start_service || log "tailscaled did not start; check /userdata/system/logs/tailscaled.log"
  log "installed version=$version"
}

do_update() {
  arch="$(detect_arch)" || fail "Unsupported architecture for Tailscale static binaries: $(uname -m)"
  current="$(installed_version 2>/dev/null || true)"
  target="$(latest_version)"
  if [ -z "$target" ]; then
    log "Could not discover the current Tailscale version; keeping $current."
    write_service && start_service
    return 0
  fi
  if [ -n "$current" ] && [ "$current" = "$target" ]; then
    log "Tailscale $current is already current; not restarting the daemon."
    # Still make sure the service file and daemon are in place -- an upgrade
    # is also our chance to repair a drone whose service went missing.
    write_service || true
    daemon_running || start_service || true
    log "installed version=$current"
    return 0
  fi

  stage="/tmp/drone-tailscale-stage.$$"
  if ! download_into "$target" "$arch" "$stage"; then
    rm -rf "$stage"
    if [ -n "$current" ]; then
      log "Upgrade to $target failed; keeping installed $current."
      log "installed version=$current"
      return 0
    fi
    fail "Tailscale install failed."
  fi

  # Swap, keeping the outgoing binaries for rollback.
  rm -rf "$TS_BACKUP"
  if [ -d "$TS_BIN" ]; then
    cp -a "$TS_BIN" "$TS_BACKUP" 2>/dev/null || true
  fi
  mkdir -p "$TS_BIN"
  cp "$stage/tailscaled" "$stage/tailscale" "$TS_BIN/" || {
    rm -rf "$stage"
    fail "Could not install the staged Tailscale binaries."
  }
  chmod 755 "$TS_BIN/tailscaled" "$TS_BIN/tailscale"
  rm -rf "$stage"

  write_service || true
  restart_service
  if wait_for_daemon; then
    log "Upgraded Tailscale ${current:-none} -> $target"
    log "installed version=$target"
    return 0
  fi

  if [ -d "$TS_BACKUP" ]; then
    log "Tailscale $target did not come up; rolling back to ${current:-previous}."
    cp "$TS_BACKUP/tailscaled" "$TS_BACKUP/tailscale" "$TS_BIN/" 2>/dev/null || true
    chmod 755 "$TS_BIN/tailscaled" "$TS_BIN/tailscale" 2>/dev/null || true
    restart_service
    log "installed version=${current:-unknown}"
    fail "Tailscale $target failed to start; rolled back to ${current:-the previous build}."
  fi
  fail "Tailscale $target failed to start and there was no previous build to roll back to."
}

COMMAND="${1:-ensure}"
case "$COMMAND" in
  install)
    if [ -x "$TS_BIN/tailscaled" ]; then
      log "Tailscale binaries already present in $TS_BIN; keeping them."
      write_service || true
      daemon_running || start_service || true
      log "installed version=$(installed_version 2>/dev/null || echo unknown)"
    else
      do_install
    fi
    ;;
  update)
    do_update
    ;;
  ensure)
    if [ -x "$TS_BIN/tailscaled" ]; then
      do_update
    else
      do_install
    fi
    ;;
  service)
    write_service || fail "Could not write $TS_SERVICE"
    start_service || true
    log "Created service: $TS_SERVICE"
    ;;
  status)
    if [ -x "$TS_BIN/tailscale" ]; then
      echo "installed=1 version=$(installed_version 2>/dev/null || echo unknown) running=$(daemon_running && echo 1 || echo 0)"
    else
      echo "installed=0 version= running=0"
    fi
    ;;
  *)
    fail "Usage: $0 {ensure|install|update|service|status}"
    ;;
esac
