"""Drone TLS identity lifecycle: self-signed generation, rotation, metadata.

Extracted from ``drone_api.py``. ``DroneCertificateManager`` owns the drone's mTLS
identity -- it ensures a self-signed CA/client certificate exists (via ``openssl``),
can force a fresh identity on demand (rotation), and decodes its metadata. HTTPS
listeners use a replaceable leaf signed by this identity; see ``web.server_tls``.
"""

import hashlib
import os
import re
import socket
import ssl
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

try:
    from ..common.settings import Settings
    from .drone_network import _get_local_certificate_ips
    from .network_identity import (
        hostname_override_values as _hostname_override_values,
        is_ip_literal as _is_ip_literal,
    )
except ImportError:  # pragma: no cover - direct script execution fallback
    from common.settings import Settings  # type: ignore
    from transfer.drone_network import _get_local_certificate_ips  # type: ignore
    from transfer.network_identity import (  # type: ignore
        hostname_override_values as _hostname_override_values,
        is_ip_literal as _is_ip_literal,
    )


class DroneCertificateManager:
    def __init__(self, settings: Settings):
        self.settings = settings

    def ensure_certificate(self) -> dict:
        cert_file = self.settings.drone_cert_file
        key_file = self.settings.drone_key_file
        if cert_file.exists() and key_file.exists():
            metadata = self.metadata()
            if metadata.get("status") == "loaded" and metadata.get("renewal_status") != "expired":
                return metadata
        if self.settings.drone_mtls_mode == "managed":
            return {
                "status": "invalid",
                "error": "managed Drone mTLS mode requires pre-provisioned, unexpired certificate and key files",
                "cert_file": str(cert_file),
                "key_file": str(key_file),
            }
        self._generate_local_certificate(cert_file, key_file)
        return self.metadata()

    def regenerate_self_signed_certificate(self) -> dict:
        """Force a fresh self-signed certificate now (manual rotation from the admin UI).

        Paired peers pinned the previous certificate's fingerprint at pairing time, so
        they will need to re-pair after this -- same tradeoff as any other identity
        rotation. Not available in ``managed`` mTLS mode (cert/key are provisioned
        out-of-band there, not generated by this process).
        """
        if self.settings.drone_mtls_mode == "managed":
            raise ValueError("managed Drone mTLS mode uses a pre-provisioned certificate; rotate it out-of-band")
        self._generate_local_certificate(self.settings.drone_cert_file, self.settings.drone_key_file)
        return self.metadata()

    def _generate_local_certificate(self, cert_file: Path, key_file: Path) -> None:
        cert_file.parent.mkdir(parents=True, exist_ok=True)
        common_name = certificate_common_name(self.settings)
        san = ",".join(certificate_alt_names(self.settings))
        command = [
            "openssl",
            "req",
            "-x509",
            "-nodes",
            "-newkey",
            "rsa:2048",
            "-keyout",
            str(key_file),
            "-out",
            str(cert_file),
            "-days",
            str(max(1, int(self.settings.drone_cert_days))),
            "-subj",
            f"/CN={common_name}",
            "-addext",
            f"subjectAltName={san}",
            "-addext",
            "basicConstraints=critical,CA:TRUE",
            "-addext",
            "keyUsage=critical,digitalSignature,keyCertSign",
            "-addext",
            "extendedKeyUsage=serverAuth,clientAuth",
        ]
        try:
            subprocess.run(command, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except (FileNotFoundError, subprocess.CalledProcessError) as error:
            raise RuntimeError(f"failed to generate Drone certificate with openssl: {error}") from error

    def metadata(self) -> dict:
        cert_file = self.settings.drone_cert_file
        if not cert_file.exists():
            return {"status": "missing", "cert_file": str(cert_file)}
        try:
            pem = cert_file.read_text(encoding="utf-8", errors="ignore")
            der = ssl.PEM_cert_to_DER_cert(pem)
            decoded = ssl._ssl._test_decode_cert(str(cert_file))  # type: ignore[attr-defined]
        except Exception as error:
            return {"status": "invalid", "error": str(error), "cert_file": str(cert_file)}

        def _name(items) -> str:
            parts = []
            for group in items or []:
                for key, value in group:
                    parts.append(f"{key}={value}")
            return ", ".join(parts)

        san = []
        for kind, value in decoded.get("subjectAltName", ()):
            if kind.lower() == "dns":
                san.append(value)
        not_after = decoded.get("notAfter")
        renewal_status = "unknown"
        try:
            expires_at = datetime.strptime(not_after, "%b %d %H:%M:%S %Y %Z").replace(tzinfo=timezone.utc)
            days_left = (expires_at - datetime.now(timezone.utc)).days
            renewal_status = "expired" if days_left < 0 else ("renew_soon" if days_left <= 30 else "valid")
        except Exception:
            days_left = None
        return {
            "status": "loaded",
            "source": "local_self_signed",
            "fingerprint": hashlib.sha256(der).hexdigest(),
            "public_certificate": pem,
            "subject": _name(decoded.get("subject")),
            "issuer": _name(decoded.get("issuer")),
            "serial_number": decoded.get("serialNumber"),
            "san": san,
            "valid_from": decoded.get("notBefore"),
            "valid_until": not_after,
            "days_until_expiry": days_left,
            "registered_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
            "last_seen": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
            "renewal_status": renewal_status,
            "identity": self.settings.device_id,
            "mtls_enabled": self.settings.drone_mtls_enabled,
            "mtls_mode": self.settings.drone_mtls_mode,
        }


def certificate_common_name(settings: Settings) -> str:
    # A MAC-like device id contains colons, which are legal in an X.509 CN but
    # invalid in a DNS SAN and make strict OpenSSL verification reject a leaf.
    identity = re.sub(r"[^A-Za-z0-9.-]+", "-", settings.device_id).strip("-.") or "drone"
    return f"batocera-drone-{identity}"


def certificate_alt_names(settings: Settings) -> list[str]:
    """Return stable hostnames plus current LAN/tailnet addresses for TLS.

    The self-signed Drone identity is long-lived and pinned by peers. The web
    server leaf certificate may be reissued as this set grows without changing
    that identity. Unqualified hostnames gain their mDNS ``.local`` form so the
    standard ``https://batocera.local`` URL validates after the Drone CA is
    trusted by a client.
    """
    common_name = certificate_common_name(settings)
    alt_names = [f"DNS:{common_name}", "DNS:localhost", "IP:127.0.0.1"]

    hostnames = []
    for loader in (socket.gethostname, socket.getfqdn):
        try:
            value = str(loader() or "").strip().rstrip(".")
        except OSError:
            value = ""
        if value:
            hostnames.append(value)
    hostnames.extend(_hostname_override_values(settings))

    for hostname in hostnames:
        if _is_ip_literal(hostname):
            alt_names.append(f"IP:{hostname.strip('[]')}")
            continue
        alt_names.append(f"DNS:{hostname}")
        if "." not in hostname:
            alt_names.append(f"DNS:{hostname}.local")
    for ip in _get_local_certificate_ips():
        alt_names.append(f"IP:{ip}")
    return list(dict.fromkeys(alt_names))
