#!/bin/sh
set -e

WORK_DIR="/userdata/system/drone-app"

BATOCERA_VERSION=""
if command -v batocera-version >/dev/null 2>&1; then
  BATOCERA_VERSION="$(batocera-version 2>/dev/null | head -1 | tr -d '[:space:]')"
fi

if [ -z "$BATOCERA_VERSION" ]; then
  if [ -f /usr/share/batocera/batocera.version ]; then
    BATOCERA_VERSION="$(cat /usr/share/batocera/batocera.version | head -1 | tr -d '[:space:]')"
  elif [ -f /etc/batocera-release ]; then
    BATOCERA_VERSION="$(cat /etc/batocera-release | head -1 | tr -d '[:space:]')"
  fi
fi

MAJOR_VERSION="$(echo "$BATOCERA_VERSION" | sed 's/^\([0-9]*\).*/\1/')"

USE_LEGACY_METHOD=false
if [ -n "$MAJOR_VERSION" ] && [ "$MAJOR_VERSION" -lt 43 ] 2>/dev/null; then
  USE_LEGACY_METHOD=true
fi

echo "============================================"
echo " Batocera Drone Installer"
echo "============================================"
echo "Detected Batocera version: ${BATOCERA_VERSION:-unknown}"
echo ""

mkdir -p "$WORK_DIR"

echo ""
echo "Drone runs as root. The service startup only creates Drone runtime directories;"
echo "it does not rewrite ROM, BIOS, emulator, or Batocera config permissions."

if [ "$USE_LEGACY_METHOD" = false ]; then
  echo ""
  echo "Installing for Batocera v43+ ..."

  SERVICES_DIR="/userdata/system/services"
  SERVICE_FILE="${SERVICES_DIR}/DRONE_SERVER"

  mkdir -p "$SERVICES_DIR"

  cat > "$SERVICE_FILE" << 'SERVICEBLOCK'
#!/bin/sh
# Thin Drone service launcher (generated by batocera_install.sh).
#
# All service-side logic lives in the versioned app bundle at
# app/service_bootstrap.sh, which auto-updates with every Drone release. This
# shim only ensures that bundle is present and then delegates to it, so
# service-side changes (runtime directory setup, privileged controls, and the
# supervisor) apply automatically on the next service restart
# without re-running batocera_install.sh on each machine.

WORK_DIR="/userdata/system/drone-app"
ACTION="$1"
STARTUP_LOG="/userdata/system/logs/drone-app/startup.log"
BOOTSTRAP="$WORK_DIR/app/service_bootstrap.sh"
RUN_WEB_NOW_URL="https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/run_web_now.sh"
ARCHIVE_URL="https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/drone-app.tar.gz"

ensure_bundle() {
  [ -f "$BOOTSTRAP" ] && return 0
  mkdir -p "$(dirname "$STARTUP_LOG")"
  echo "[drone-service] Service bootstrap missing; downloading Drone app bundle..." | tee -a "$STARTUP_LOG"
  runner="/tmp/drone-bootstrap-fetch.$$"
  if curl -fsSL --connect-timeout 10 --max-time 120 -o "$runner" "$RUN_WEB_NOW_URL"; then
    chmod 755 "$runner" 2>/dev/null || true
    DRONE_APP_STAGE_ONLY=1 DRONE_APP_WORK_DIR="$WORK_DIR" DRONE_APP_ARCHIVE_URL="$ARCHIVE_URL" bash "$runner" >> "$STARTUP_LOG" 2>&1 || true
    rm -f "$runner"
  else
    rm -f "$runner"
    echo "[drone-service] Failed to download Drone app bundle for bootstrap." | tee -a "$STARTUP_LOG"
  fi
}

case "$ACTION" in
  start|restart)
    ensure_bundle
    ;;
esac

if [ -f "$BOOTSTRAP" ]; then
  exec sh "$BOOTSTRAP" "$ACTION"
fi

echo "[drone-service] Drone service bootstrap unavailable at $BOOTSTRAP"
exit 1
SERVICEBLOCK

  chmod +x "$SERVICE_FILE"

  echo "✓ Created service: $SERVICE_FILE"

  echo ""
  echo "Downloading latest Drone app bundle..."
  RUNNER="/tmp/drone-run-web-now-install.$$"
  if curl -fsSL --connect-timeout 10 --max-time 120 -o "$RUNNER" https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/run_web_now.sh; then
    chmod 755 "$RUNNER" 2>/dev/null || true
    "$SERVICE_FILE" stop >/dev/null 2>&1 || true
    DRONE_APP_STAGE_ONLY=1 \
      DRONE_APP_WORK_DIR="$WORK_DIR" \
      DRONE_APP_ARCHIVE_URL="${DRONE_APP_ARCHIVE_URL:-https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/drone-app.tar.gz}" \
      bash "$RUNNER"
    rm -f "$RUNNER"
    echo "✓ Updated Drone app bundle in $WORK_DIR"
  else
    rm -f "$RUNNER"
    echo "Could not download latest Drone app bundle now; service will download it on next startup if the local app is invalid."
  fi

  echo ""
  echo "Enabling Drone service for automatic startup..."
  if command -v batocera-services >/dev/null 2>&1; then
    if batocera-services enable DRONE_SERVER; then
      echo "✓ Drone service enabled"
    else
      echo "Could not enable DRONE_SERVER with batocera-services."
      exit 1
    fi

    echo ""
    echo "Starting Drone service so it is ready immediately..."
    if batocera-services start DRONE_SERVER; then
      echo "✓ Drone service started"
    else
      echo "batocera-services could not start DRONE_SERVER; trying the service script directly..."
      if "$SERVICE_FILE" start; then
        echo "✓ Drone service started"
      else
        echo "Could not start Drone service automatically. Start it manually with:"
        echo "  batocera-services start DRONE_SERVER"
      fi
    fi
  else
    echo "batocera-services is unavailable; DRONE_SERVER cannot be enabled for automatic startup."
    exit 1
  fi

else
  echo ""
  echo "Installing for Batocera < v43 ..."

  CUSTOM_SH="/userdata/system/custom.sh"

  if [ ! -f "$CUSTOM_SH" ]; then
    echo '#!/bin/sh' > "$CUSTOM_SH"
    chmod +x "$CUSTOM_SH"
  elif [ ! -x "$CUSTOM_SH" ]; then
    chmod +x "$CUSTOM_SH"
  fi

  if grep -q "Batocera-Fleet-Federation/batocera.drone" "$CUSTOM_SH" 2>/dev/null; then
    echo "Drone startup block already exists in $CUSTOM_SH. Skipping."
  else
    cat >> "$CUSTOM_SH" << 'SERVICEBLOCK'

# Run Drone Web Server: https://raw.githubusercontent.com/Batocera-Fleet-Federation/batocera.drone
(
  max_attempts="${DRONE_NETWORK_WAIT_ATTEMPTS:-12}"
  attempt=1
  while [ "$attempt" -le "$max_attempts" ]; do
    if curl -fsI --connect-timeout 5 --max-time 10 https://github.com >/dev/null 2>&1; then
      break
    fi
    if ping -c 1 -W 2 8.8.8.8 >/dev/null 2>&1; then
      break
    fi
    attempt=$((attempt + 1))
    sleep 5
  done

  curl -fsSL --connect-timeout 10 --max-time 120 https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/run_web_now.sh | bash
) &

SERVICEBLOCK

    echo "✓ Appended startup block to $CUSTOM_SH"
  fi
fi

# ----------------------------------------------------------------------------
# Tailscale mesh (optional, on by default; skip with DRONE_SKIP_TAILSCALE=1)
#
# Installs the static tailscaled/tailscale binaries under /userdata (survives
# Batocera OS updates) and a DRONE_TAILNET service, so drones in different
# houses reach each other -- and your phone reaches every drone -- with no
# port-forwarding. The daemon is inert until the device is enrolled: pass
# TS_AUTHKEY=tskey-auth-... to this installer for hands-free enrollment, or
# run the printed "tailscale up" command once afterwards.
# ----------------------------------------------------------------------------

TS_DIR="/userdata/system/tailscale"
TS_SERVICE="/userdata/system/services/DRONE_TAILNET"
TS_SOCKET="/var/run/tailscale/tailscaled.sock"
TS_FALLBACK_VERSION="1.80.0"

write_tailnet_service() {
  mkdir -p "$(dirname "$TS_SERVICE")"
  cat > "$TS_SERVICE" << 'TAILNETBLOCK'
#!/bin/sh
# Tailscale mesh daemon for the Batocera Drone fleet (generated by batocera_install.sh).
# Self-contained on purpose: unlike DRONE_SERVER (a thin shim into the versioned
# app bundle), tailscaled supervision does not change with Drone releases.

TS_DIR="/userdata/system/tailscale"
STATE_DIR="$TS_DIR/state"
LOG_FILE="/userdata/system/logs/tailscaled.log"
PID_FILE="/tmp/drone-tailscaled.pid"
SOCKET_DIR="/var/run/tailscale"

is_running() {
  [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null
}

start() {
  if [ ! -x "$TS_DIR/bin/tailscaled" ]; then
    echo "[drone-tailnet] tailscaled is not installed at $TS_DIR/bin" >&2
    exit 1
  fi
  if is_running; then
    exit 0
  fi
  mkdir -p "$STATE_DIR" "$SOCKET_DIR" "$(dirname "$LOG_FILE")"
  modprobe tun 2>/dev/null || true
  if [ ! -c /dev/net/tun ]; then
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200 2>/dev/null || true
  fi
  TUN_FLAG="--tun=tailscale0"
  if [ ! -c /dev/net/tun ]; then
    # Inbound tailnet connections (phone -> drone UI, peer -> /peer/*) still
    # work via the userspace netstack; only this drone's own outbound dials to
    # tailnet addresses are unavailable, and transfers fall back to the other
    # transport tiers.
    echo "[drone-tailnet] /dev/net/tun unavailable; using userspace networking" >> "$LOG_FILE"
    TUN_FLAG="--tun=userspace-networking"
  fi
  nohup "$TS_DIR/bin/tailscaled" \
    --statedir="$STATE_DIR" \
    --socket="$SOCKET_DIR/tailscaled.sock" \
    "$TUN_FLAG" >> "$LOG_FILE" 2>&1 &
  echo $! > "$PID_FILE"
  echo "[drone-tailnet] tailscaled started (pid $(cat "$PID_FILE"))"
}

stop() {
  if [ -f "$PID_FILE" ]; then
    kill "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null || true
    rm -f "$PID_FILE"
  fi
  pkill -f "$TS_DIR/bin/tailscaled" 2>/dev/null || true
  echo "[drone-tailnet] tailscaled stopped"
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) stop; sleep 1; start ;;
  status)
    if is_running; then
      echo "[drone-tailnet] running (pid $(cat "$PID_FILE"))"
    else
      echo "[drone-tailnet] not running"
      exit 1
    fi
    ;;
  *) echo "Usage: $0 {start|stop|restart|status}"; exit 2 ;;
esac
TAILNETBLOCK
  chmod +x "$TS_SERVICE"
}

install_tailscale_mesh() {
  if [ "${DRONE_SKIP_TAILSCALE:-0}" = "1" ]; then
    echo "Skipping Tailscale mesh setup (DRONE_SKIP_TAILSCALE=1)."
    return 0
  fi

  echo ""
  echo "Setting up the Tailscale mesh (tailnet) ..."

  case "$(uname -m)" in
    x86_64) TS_ARCH="amd64" ;;
    aarch64) TS_ARCH="arm64" ;;
    armv7l|armv6l) TS_ARCH="arm" ;;
    i686|i586) TS_ARCH="386" ;;
    riscv64) TS_ARCH="riscv64" ;;
    *)
      echo "Unsupported architecture for Tailscale static binaries: $(uname -m); skipping mesh setup."
      return 1
      ;;
  esac

  if [ -x "$TS_DIR/bin/tailscaled" ]; then
    echo "Tailscale binaries already present in $TS_DIR/bin; keeping them."
  else
    TS_VERSION="${DRONE_TAILSCALE_VERSION:-}"
    if [ -z "$TS_VERSION" ]; then
      TS_VERSION="$(curl -fsSL --connect-timeout 10 --max-time 30 "https://pkgs.tailscale.com/stable/?mode=json" 2>/dev/null \
        | sed -n 's/.*"Version":[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
    fi
    if [ -z "$TS_VERSION" ]; then
      TS_VERSION="$TS_FALLBACK_VERSION"
      echo "Could not discover the current Tailscale version; using pinned fallback $TS_VERSION."
    fi

    TS_TARBALL="tailscale_${TS_VERSION}_${TS_ARCH}.tgz"
    TS_TMP="/tmp/drone-tailscale-install.$$"
    echo "Downloading Tailscale $TS_VERSION for $TS_ARCH ..."
    if ! curl -fsSL --connect-timeout 10 --max-time 300 -o "$TS_TMP.tgz" "https://pkgs.tailscale.com/stable/$TS_TARBALL"; then
      rm -f "$TS_TMP.tgz"
      echo "Could not download $TS_TARBALL; skipping mesh setup (re-run the installer to retry)."
      return 1
    fi
    mkdir -p "$TS_TMP" "$TS_DIR/bin"
    if ! tar -xzf "$TS_TMP.tgz" -C "$TS_TMP"; then
      rm -rf "$TS_TMP" "$TS_TMP.tgz"
      echo "Could not extract $TS_TARBALL; skipping mesh setup."
      return 1
    fi
    cp "$TS_TMP"/tailscale_*/tailscaled "$TS_TMP"/tailscale_*/tailscale "$TS_DIR/bin/"
    chmod 755 "$TS_DIR/bin/tailscaled" "$TS_DIR/bin/tailscale"
    rm -rf "$TS_TMP" "$TS_TMP.tgz"
    echo "✓ Installed tailscaled + tailscale to $TS_DIR/bin"
  fi

  write_tailnet_service
  echo "✓ Created service: $TS_SERVICE"

  if [ "$USE_LEGACY_METHOD" = false ] && command -v batocera-services >/dev/null 2>&1; then
    batocera-services enable DRONE_TAILNET >/dev/null 2>&1 || true
    batocera-services start DRONE_TAILNET >/dev/null 2>&1 || "$TS_SERVICE" start || true
    echo "✓ DRONE_TAILNET service enabled and started"
  else
    if ! grep -q "Start Drone tailnet mesh" "$CUSTOM_SH" 2>/dev/null; then
      cat >> "$CUSTOM_SH" << 'TAILNETSTART'

# Start Drone tailnet mesh: Batocera-Fleet-Federation/batocera.drone (tailscaled)
(
  sh /userdata/system/services/DRONE_TAILNET start
) &

TAILNETSTART
      echo "✓ Appended tailnet startup block to $CUSTOM_SH"
    fi
    "$TS_SERVICE" start || true
  fi

  # Give the daemon a moment to come up before talking to it.
  sleep 2

  TS_AUTH="${TS_AUTHKEY:-${DRONE_TAILSCALE_AUTHKEY:-}}"
  TS_HOSTNAME="$(hostname | tr 'A-Z' 'a-z')"
  if "$TS_DIR/bin/tailscale" --socket="$TS_SOCKET" status >/dev/null 2>&1; then
    echo "✓ This drone is already enrolled in the tailnet."
  elif [ -n "$TS_AUTH" ]; then
    echo "Enrolling in the tailnet with the provided auth key ..."
    # --accept-dns=false: keep Batocera's resolv.conf untouched (the Drone
    # tailnet integration works on raw 100.x addresses, not MagicDNS names).
    if "$TS_DIR/bin/tailscale" --socket="$TS_SOCKET" up --authkey="$TS_AUTH" --hostname="$TS_HOSTNAME" --accept-dns=false --netfilter-mode=off; then
      echo "✓ Enrolled in the tailnet as '$TS_HOSTNAME'"
    else
      echo "Tailnet enrollment failed; run it manually later:"
      echo "  $TS_DIR/bin/tailscale --socket=$TS_SOCKET up --accept-dns=false --netfilter-mode=off"
    fi
  else
    echo ""
    echo "Tailscale is installed and running but this drone is NOT enrolled yet."
    echo "Enroll it once (prints a login URL to open from any browser):"
    echo "  $TS_DIR/bin/tailscale --socket=$TS_SOCKET up --hostname=$TS_HOSTNAME --accept-dns=false --netfilter-mode=off"
    echo "Or re-run this installer with TS_AUTHKEY=tskey-auth-... for hands-free enrollment."
  fi
  return 0
}

install_ports_client() {
  if [ "${DRONE_SKIP_PORTS_CLIENT:-0}" = "1" ]; then
    echo "Skipping the Ports client install (DRONE_SKIP_PORTS_CLIENT=1)."
    return 0
  fi

  case "$(uname -m)" in
    x86_64) BUNDLE_ARCH="x86_64" ;;
    aarch64) BUNDLE_ARCH="aarch64" ;;
    *)
      echo "No Ports client bundle for this architecture ($(uname -m)) yet; skipping."
      return 0
      ;;
  esac

  # A DRONE_PORTS_CLIENT_BUNDLE override or a bundle pre-built by
  # ports-client/scripts/build_release_bundle.sh and left next to the
  # installer both win over a download, mainly so local testing (e.g.
  # ports-client/scripts/run_client_now.sh's own dev loop, or a one-off
  # `DRONE_PORTS_CLIENT_BUNDLE=... bash batocera_install.sh` against a
  # locally-built tarball) never needs network access. Otherwise this pulls
  # the matching release asset, mirroring install_tailscale_mesh()'s
  # download-with-a-clear-retry-message pattern above.
  INSTALLER_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
  BUNDLE_TARBALL="${DRONE_PORTS_CLIENT_BUNDLE:-$INSTALLER_DIR/../ports-client/dist/batocera-drone-client-$BUNDLE_ARCH.tar.gz}"
  PC_DOWNLOADED_TMP=""

  if [ -f "$BUNDLE_TARBALL" ]; then
    echo "Using local Ports client bundle at $BUNDLE_TARBALL."
  else
    PC_URL="https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/batocera-drone-client-$BUNDLE_ARCH.tar.gz"
    PC_DOWNLOADED_TMP="/tmp/drone-ports-client-install.$$.tar.gz"
    echo "Downloading the Ports client bundle for $BUNDLE_ARCH ..."
    if ! curl -fsSL --connect-timeout 10 --max-time 300 -o "$PC_DOWNLOADED_TMP" "$PC_URL"; then
      rm -f "$PC_DOWNLOADED_TMP"
      echo "Could not download the Ports client bundle ($PC_URL); skipping (re-run the installer to retry)."
      echo "  (or build one locally with ports-client/scripts/build_release_bundle.sh $BUNDLE_ARCH, or set DRONE_PORTS_CLIENT_BUNDLE=/path/to/bundle.tar.gz)"
      return 1
    fi
    BUNDLE_TARBALL="$PC_DOWNLOADED_TMP"
  fi

  PORTS_DIR="/userdata/roms/ports"
  mkdir -p "$PORTS_DIR"
  if ! tar -xzf "$BUNDLE_TARBALL" -C "$PORTS_DIR"; then
    echo "Failed to extract the Ports client bundle."
    [ -n "$PC_DOWNLOADED_TMP" ] && rm -f "$PC_DOWNLOADED_TMP"
    return 1
  fi
  [ -n "$PC_DOWNLOADED_TMP" ] && rm -f "$PC_DOWNLOADED_TMP"
  chmod +x "$PORTS_DIR/batocera-drone-client.sh"
  PORTS_GAMELIST_HELPER="$PORTS_DIR/.data/batocera-drone-client/client/gamelist_integration.py"
  if [ -f "$PORTS_GAMELIST_HELPER" ]; then
    if python3 "$PORTS_GAMELIST_HELPER" "$PORTS_DIR"; then
      # ES caches gamelist metadata in memory. Its localhost-only service
      # applies this external edit without restarting the frontend or ending
      # a running game. If ES is not running yet, it will read the file later.
      if ! curl -fsS --connect-timeout 2 --max-time 5 http://127.0.0.1:1234/reloadgames >/dev/null 2>&1; then
        echo "Ports artwork is installed; EmulationStation will load it on its next start."
      fi
    else
      echo "Ports client installed, but its EmulationStation artwork metadata could not be refreshed."
    fi
  fi
  echo "✓ Installed the Drone Ports client to $PORTS_DIR (rescan Ports in EmulationStation to see it)"
  return 0
}

if ! install_ports_client; then
  echo "Ports client install did not complete; the Drone install itself is unaffected."
fi

CUSTOM_SH="${CUSTOM_SH:-/userdata/system/custom.sh}"
if ! install_tailscale_mesh; then
  echo "Tailscale mesh setup did not complete; the Drone install itself is unaffected."
fi

echo ""
echo "Installation complete!"
echo ""
echo "Drone runs as root and can access Batocera files as root."
echo "The installer does not maintain a read/write allowlist or rewrite ROM,"
echo "BIOS, emulator, or Batocera config permissions."

# Show the exact local URL the Drone resolves at, front and center, so the user
# knows precisely where to open it from any device on their network.
DRONE_LOCAL_URL="https://$(hostname | tr 'A-Z' 'a-z').local"
DRONE_TAILNET_IP=""
if [ -x "$TS_DIR/bin/tailscale" ]; then
  DRONE_TAILNET_IP="$("$TS_DIR/bin/tailscale" --socket="$TS_SOCKET" ip -4 2>/dev/null | head -1)"
fi
echo ""
printf '\033[1;32m'
echo "======================================================================"
echo ""
echo "   >>>  OPEN YOUR DRONE IN A BROWSER AT:  <<<"
echo ""
echo "        ${DRONE_LOCAL_URL}"
if [ -n "$DRONE_TAILNET_IP" ]; then
  echo ""
  echo "   From anywhere via the tailnet (Tailscale app on your phone):"
  echo "        https://${DRONE_TAILNET_IP}"
fi
echo ""
echo "   Works from any phone or computer on the same network."
echo "   Sign in with username 'batocera' and password 'linux'."
echo "   (If it does not load yet, start the DRONE_SERVER service or reboot.)"
echo ""
echo "======================================================================"
printf '\033[0m'
echo ""
