#!/bin/sh
set -e

DRONE_USER="drone-app"
DRONE_GROUP="drone-app"
DRONE_UID="999"
DRONE_GID="999"
WORK_DIR="/userdata/system/drone-app"

BATOCERA_VERSION=""
if command -v batocera-version >/dev/null 2>&1; then
  BATOCERA_VERSION="$(batocera-version 2>/dev/null | head -1 | tr -d '[:space:]')"
fi

if [ -z "$BATOCERA_VERSION" ]; then
  if [ -f /usr/share/batocera/batocera.version ]; then
    BATOCERA_VERSION="$(cat /usr/share/batocera/batocera.version | head -1 | tr -d '[:space:]')"
  elif [ -f /etc/batocera-release ]; then
    BATOCERA_VERSION="$(cat /etc/batocera-release | head -1 | tr -d '[:space:]')"
  fi
fi

MAJOR_VERSION="$(echo "$BATOCERA_VERSION" | sed 's/^\([0-9]*\).*/\1/')"

USE_LEGACY_METHOD=false
if [ -n "$MAJOR_VERSION" ] && [ "$MAJOR_VERSION" -lt 43 ] 2>/dev/null; then
  USE_LEGACY_METHOD=true
fi

echo "============================================"
echo " Batocera Drone Installer"
echo "============================================"
echo "Detected Batocera version: ${BATOCERA_VERSION:-unknown}"
echo ""

mkdir -p "$WORK_DIR"

echo ""
echo "Permissions are applied at service startup via"
echo "the ensure_permissions() function in DRONE_SERVER."

if [ "$USE_LEGACY_METHOD" = false ]; then
  echo ""
  echo "Installing for Batocera v43+ ..."

  SERVICES_DIR="/userdata/system/services"
  SERVICE_FILE="${SERVICES_DIR}/DRONE_SERVER"

  mkdir -p "$SERVICES_DIR"

  cat > "$SERVICE_FILE" << 'SERVICEBLOCK'
#!/bin/sh
# Thin Drone service launcher (generated by batocera_install.sh).
#
# All service-side logic lives in the versioned app bundle at
# app/service_bootstrap.sh, which auto-updates with every Drone release. This
# shim only ensures that bundle is present and then delegates to it, so
# service-side changes (drone-app user/permissions, the privileged control
# worker, the supervisor) apply automatically on the next service restart
# without re-running batocera_install.sh on each machine.

WORK_DIR="/userdata/system/drone-app"
ACTION="$1"
STARTUP_LOG="/userdata/system/logs/drone-app/startup.log"
BOOTSTRAP="$WORK_DIR/app/service_bootstrap.sh"
RUN_NOW_URL="https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/run_now.sh"
ARCHIVE_URL="https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/drone-app.tar.gz"

ensure_bundle() {
  [ -f "$BOOTSTRAP" ] && return 0
  mkdir -p "$(dirname "$STARTUP_LOG")"
  echo "[drone-service] Service bootstrap missing; downloading Drone app bundle..." | tee -a "$STARTUP_LOG"
  runner="/tmp/drone-bootstrap-fetch.$$"
  if curl -fsSL --connect-timeout 10 --max-time 120 -o "$runner" "$RUN_NOW_URL"; then
    chmod 755 "$runner" 2>/dev/null || true
    DRONE_APP_STAGE_ONLY=1 DRONE_APP_WORK_DIR="$WORK_DIR" DRONE_APP_ARCHIVE_URL="$ARCHIVE_URL" bash "$runner" >> "$STARTUP_LOG" 2>&1 || true
    rm -f "$runner"
  else
    rm -f "$runner"
    echo "[drone-service] Failed to download Drone app bundle for bootstrap." | tee -a "$STARTUP_LOG"
  fi
}

case "$ACTION" in
  start|restart)
    ensure_bundle
    ;;
esac

if [ -f "$BOOTSTRAP" ]; then
  exec sh "$BOOTSTRAP" "$ACTION"
fi

echo "[drone-service] Drone service bootstrap unavailable at $BOOTSTRAP"
exit 1
SERVICEBLOCK

  chmod +x "$SERVICE_FILE"

  echo "✓ Created service: $SERVICE_FILE"

  echo ""
  echo "Downloading latest Drone app bundle..."
  RUNNER="/tmp/drone-run-now-install.$$"
  if curl -fsSL --connect-timeout 10 --max-time 120 -o "$RUNNER" https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/run_now.sh; then
    chmod 755 "$RUNNER" 2>/dev/null || true
    APP_WAS_RUNNING=false
    if [ -f /tmp/drone-server.pid ]; then
      EXISTING_PID="$(cat /tmp/drone-server.pid 2>/dev/null || true)"
      if [ -n "$EXISTING_PID" ] && kill -0 "$EXISTING_PID" 2>/dev/null; then
        APP_WAS_RUNNING=true
      fi
    fi
    if lsof -i:"${HTTPS_PORT:-443}" >/dev/null 2>&1; then
      APP_WAS_RUNNING=true
    fi
    "$SERVICE_FILE" stop >/dev/null 2>&1 || true
    DRONE_APP_STAGE_ONLY=1 \
      DRONE_APP_WORK_DIR="$WORK_DIR" \
      DRONE_APP_ARCHIVE_URL="${DRONE_APP_ARCHIVE_URL:-https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/drone-app.tar.gz}" \
      bash "$RUNNER"
    rm -f "$RUNNER"
    chown -R root:"$DRONE_GROUP" "$WORK_DIR" 2>/dev/null || true
    chmod -R 775 "$WORK_DIR" 2>/dev/null || true
    echo "✓ Updated Drone app bundle in $WORK_DIR"
    if [ "$APP_WAS_RUNNING" = true ]; then
      echo "Restarting Drone service with updated app bundle..."
      "$SERVICE_FILE" start
    fi
  else
    rm -f "$RUNNER"
    echo "Could not download latest Drone app bundle now; service will download it on next startup if the local app is invalid."
  fi

  echo "Start now with:"
  echo "  $SERVICE_FILE start"

else
  echo ""
  echo "Installing for Batocera < v43 ..."

  CUSTOM_SH="/userdata/system/custom.sh"

  if [ ! -f "$CUSTOM_SH" ]; then
    echo '#!/bin/sh' > "$CUSTOM_SH"
    chmod +x "$CUSTOM_SH"
  elif [ ! -x "$CUSTOM_SH" ]; then
    chmod +x "$CUSTOM_SH"
  fi

  if grep -q "Batocera-Fleet-Federation/batocera.drone" "$CUSTOM_SH" 2>/dev/null; then
    echo "Drone startup block already exists in $CUSTOM_SH. Skipping."
  else
    cat >> "$CUSTOM_SH" << 'SERVICEBLOCK'

# Run Drone Web Server: https://raw.githubusercontent.com/Batocera-Fleet-Federation/batocera.drone
(
  max_attempts="${DRONE_NETWORK_WAIT_ATTEMPTS:-12}"
  attempt=1
  while [ "$attempt" -le "$max_attempts" ]; do
    if curl -fsI --connect-timeout 5 --max-time 10 https://github.com >/dev/null 2>&1; then
      break
    fi
    if ping -c 1 -W 2 8.8.8.8 >/dev/null 2>&1; then
      break
    fi
    attempt=$((attempt + 1))
    sleep 5
  done

  curl -fsSL --connect-timeout 10 --max-time 120 https://github.com/Batocera-Fleet-Federation/batocera.drone/releases/latest/download/run_now.sh | su -s /bin/sh -c "bash" drone-app
) &

SERVICEBLOCK

    echo "✓ Appended startup block to $CUSTOM_SH"
  fi
fi

echo ""
echo "Installation complete!"
echo ""
echo "drone-app can read:"
echo "  /userdata/system/configs/PCSX2/**"
echo ""
echo "drone-app can write to:"
echo "  /userdata/roms/*/images/"
echo "  /userdata/roms/*/videos/"
echo "  /userdata/roms/*/manuals/"
echo "  /userdata/roms/*/{downloaded_images,covers,media}/"
echo "  /userdata/roms/*/gamelist.xml"
echo "  /userdata/system/drone-app/"
echo "  /userdata/system/drone-app/certs/"
echo "  /userdata/system/certs/"
echo "  /userdata/system/logs/drone-app/"
echo ""
echo "ROM files and Batocera system config remain read-only to drone-app."

# Show the exact local URL the Drone resolves at, front and center, so the user
# knows precisely where to open it from any device on their network.
DRONE_LOCAL_URL="https://$(hostname | tr 'A-Z' 'a-z').local"
echo ""
printf '\033[1;32m'
echo "======================================================================"
echo ""
echo "   >>>  OPEN YOUR DRONE IN A BROWSER AT:  <<<"
echo ""
echo "        ${DRONE_LOCAL_URL}"
echo ""
echo "   Works from any phone or computer on the same network."
echo "   Sign in with username 'batocera' and password 'linux'."
echo "   (If it does not load yet, start the DRONE_SERVER service or reboot.)"
echo ""
echo "======================================================================"
printf '\033[0m'
echo ""
